### PR TITLE
feat: Add `debug` option

### PR DESCRIPTION
**Pull request by esafev**
Just added debug option for `init` method.

### CODE REVIEW

**Comment by esafev** [comment]
Hi @hereismass! You can see this PR? Thanks!🖖

And sorry for this mention, but i can't add you to reviewers.

**Comment by arrwhidev** [comment]
Hey @esafev 👋 

Thanks for the MR, we will review this as soon as we can 👍

**Comment by esafev** [comment]
Sorry guys, is there any news on this MR? 

сс @arrwhidev @hereismass

**Comment by arrwhidev** [comment]
Hey @esafev, apologies for the delay. Your MR has been merged, and v1.0.6 is now available in npm.

**Pull request merged**
