### PR TITLE
feat: Add support for Events API

### LINKED ISSUE #9: Add Support for Events API
We would prefer to use this package instead of the generated script tag via the site. Unfortunately, there is no formal support for adding events in this package that matches the Events API [doc](https://help.hotjar.com/hc/en-us/articles/4405109971095-Events-API-Reference) on the hotjar site.

Workaround is to import `executeHotjarCommand` from utils (awkward) and override the provided type to use the 'event' command (also awkward).

Are there any plans to improve support in this SDK? It would be a much nicer experience in web apps than the current auto-generated old-school script tag...

Thanks!

### PR DESCRIPTION
**Pull request by bobbyg603**
Fixes #9

### CODE REVIEW

**Comment by bobbyg603** [comment]
hi @hereismass, is this repo accepting contributions? do you need anything else from me to get this merged? please let me know.

**Comment by hereismass** [comment]
Hey, sorry for the delay, did not see the PR :)
the changes looks good. 

cc @arrwhidev for approval as I am not working on this area anymore

**Comment by bobbyg603** [comment]
@hereismass thank you!

**Comment by arrwhidev** [comment]
Hey @bobbyg603 👋 

Thanks for the PR, it looks good.

Can you please update the README and the demo before I approve?

Thank you.

**Comment by bobbyg603** [comment]
> Hey @bobbyg603 👋
> 
> Thanks for the PR, it looks good.
> 
> Can you please update the README and the demo before I approve?
> 
> Thank you.

Sure thing, I'll amend the commit in the near future. Thanks for the review!

**Comment by bobbyg603** [comment]
> Hey @bobbyg603 👋
> 
> Thanks for the PR, it looks good.
> 
> Can you please update the README and the demo before I approve?
> 
> Thank you.

Hi @arrwhidev, I've amended the commit. I think logging an event for an error is a really powerful use case (we use this a lot at BugSplat), however, I'll admit it's a bit awkward to click the button and see a danger alert in the demo. Please let me know if you'd like me to show a different example. Thanks!

**Comment by bobbyg603** [comment]
Hi @arrwhidev would love to get this merged so we could use the official hotjar package and deprecate our custom version. Please let me know if you need anything from me in order to get this merged. Thanks!

**Pull request merged**
